server {
    listen 80;
    server_name _;

    root /home/container/www;
    index index.php index.html;

    pid /home/container/nginx.pid;

    client_body_temp_path /home/container/tmp;
    proxy_temp_path /home/container/tmp;
    fastcgi_temp_path /home/container/tmp;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
